---
- hosts: webservers
  serial: 5
  pre_tasks:
   - name: take out of load balancer pool
     command: /usr/bin/take_out_of_pool {{ inventory_hostname }}
     delegate_to: 127.0.0.1

   roles:
     - common
     - webserver

   tasks:
     - script: /srv/qa_team/app_testing_script.sh --server {{ inventory_hostname }}
       delegate_to: testing_server

   post_tasks:
    - name: add back to load balancer pool
      command: /usr/bin/add_back_to_pool {{ inventory_hostname }}\


